### ISSUE TITLE
能添加一下微软的todo的域名吗

### ISSUE THREAD

**Issue by xu-ben** [Zxilly/OnedriveHostsGenerator#2]
兄台您好，我在网上搜到您的博客，用了您抓取到的hosts，很好用。
同时，我一直用微软的todo，最近网页版用不了了，应该也是hosts的问题，希望您能添加一下
todo.microsoft.com
感激不尽

**Comment by Zxilly** [comment]
确定是这两个域名吗

**Comment by Zxilly** [comment]
我抓了一下，客户端的应该是 `substrate.office.com`。你说的这个是网页版本的吧

**Comment by xu-ben** [comment]
No，不是substrate.office.com，就是https://todo.microsoft.com/tasks 这个，点进去登录后会跳转到to-do.live.com。手机app端一直能用，就是网页版最近不能用了。您先把这两个域名的ip给我试试？

**Comment by xu-ben** [comment]
是的，我刚试了，网页还报错，不过已经可以登进去了。感谢
