### ISSUE TITLE
域名建议

### ISSUE THREAD

**Issue by xu-ben** [Zxilly/OnedriveHostsGenerator#3]
您好，最近我在使用微软网页工具中发现三个域名也有用到，希望您能加一下
account.live.com
outlook.live.com
profile.live.com
另外，生成的hosts中的条目能排个序吗？比如按域名排，这样方便查找核对
提前感谢^_^

**Comment by Zxilly** [comment]
resolve in https://github.com/Zxilly/OnedriveHostsGenerator/commit/182341772d123ed80da93e7dde014ca624dccd91

**Comment by xu-ben** [comment]
您好，域名排序还可改进下。比如以下三个域名的顺序应该是
a.b.com
b.b.com
a.c.com
而非
a.b.com
a.c.com
b.b.com
提前感谢^_^
@Zxilly

**Comment by Zxilly** [comment]
按照字典序排应该是下面这种吧，上面这种是按什么排的

**Comment by xu-ben** [comment]
按域名排啊。
你这只是把域名字符串当作普通字符串，没当作域名。
a.b.com
b.b.com
a.c.com
a.b.com和b.b.com是同一公司同一部门的两台不同名的机器，关系更近；和a.c.com只是同名，都不在一个部门

**Comment by xu-ben** [comment]
@Zxilly

**Comment by Zxilly** [comment]
resolved in https://github.com/Zxilly/OnedriveHostsGenerator/commit/f48a5d2cdb0a9c10b4c4dc46733583cdcad4dd99
